networks:
  dev:
    driver: bridge

services:
  users_db:
    image: postgres:latest
    container_name: chess_users_db
    environment:
      - POSTGRES_DB=Users
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    networks:
      - dev
    volumes:
      - ./.containers/Users:/var/lib/postgresql/data
  games_db:
    image: postgres:latest
    container_name: chess_games_db
    environment:
      - POSTGRES_DB=GamesInfo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5434:5432
    networks:
      - dev
    volumes:
      - ./.containers/GamesInfo:/var/lib/postgresql/data
