networks:
  dev:
    driver: bridge

services:
  usersdb:
    image: postgres:latest
    container_name: chess_usersdb
    environment:
      - POSTGRES_DB=usersdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    networks:
      - dev
    volumes:
      - ./.containers/usersdb:/var/lib/postgresql/data
